PR for Maintenance Release 1.1.1
nf-core/bacass pull request #32
Opened 2020-10-14 18:45 UTC by apeltzer

This is a maintenance release mainly used to fix issues with time-outing tbl2asn (in prokka). 

- Adds some updates to tools used (where possible) - dependencies are now in larger fractions in separate containers from biocontainers to get things working more smoothly. 
- Adds JSON Schema for Workflow to launch pipeline more easily (see [here](https://nf-co.re/launch?pipeline=bacass&release=dev)

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/bacass branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/bacass)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/bacass/tree/master/.github/CONTRIBUTING.md

2020-10-15 07:59 UTC, jfy133 commented on .github/markdownlint.yml
> -no-multiple-blanks: 0
Phfff, of all the ones to remove :laughing:

2020-10-15 08:33 UTC, jfy133 approved these changes

2020-10-15 08:33 UTC, jfy133 commented on .github/workflows/awsfulltest.yml
> +            --container-overrides '{"command": ["nf-core/bacass", "-r '"${GITHUB_SHA}"' -profile test --outdir s3://'"${AWS_S3_BUCKET}"'/bacass/results-'"${GITHUB_SHA}"' -w s3://'"${AWS_S3_BUCKET}"'/
Correct this is just the default test profile, and not a larger one?

2020-10-15 08:33 UTC, jfy133 commented on CHANGELOG.md
> +* Switched out containers for many tools to make DSLv2 transition easier (escape from dependency hell)
:tada:

2020-10-15 08:33 UTC, jfy133 commented on conf/base.config
> +      time = { check_max( 160.h * task.attempt, 'time' ) }
Given these resource settings are common across multiple processes, why not have an explicit label? Saves some lines...

2020-10-15 08:33 UTC, jfy133 commented on conf/test_full.config
> +  // TODO nf-core: Give any required params for the test so that command line flags are not needed
Remove the TODOs

2020-10-15 08:33 UTC, jfy133 commented on docs/containers.md
> +Our main container is designed using [Conda](https://conda.io/) to install all tools used in nf-core/bacass. All other dedicated containers contain individual tools that are not possible to be bundle
This is a bit confusing

> Our main container is designed using [Conda](https://conda.io/) 

but 

> we cannot provide a single conda environment for the entire pipeline - please use Singularity or Docker to run your analysis!

???

I think better to just say conda can't be used because of conflicts.

2020-10-15 08:33 UTC, jfy133 commented on docs/usage.md
> -## Main Pipeline Arguments
Are you also removing because you assume it's in schema, like in cageseq?

2020-10-15 08:33 UTC, jfy133 commented on nextflow.config
> +  input = './design.csv'
Is it safe to have a default input file? Do you explicitly state somewhere that this is the default? I would rather leave it empty and have a validation check.

2020-10-18 10:02 UTC, apeltzer commented on .github/workflows/awsfulltest.yml
> +            --container-overrides '{"command": ["nf-core/bacass", "-r '"${GITHUB_SHA}"' -profile test --outdir s3://'"${AWS_S3_BUCKET}"'/bacass/results-'"${GITHUB_SHA}"' -w s3://'"${AWS_S3_BUCKET}"'/
For the moment yes - I might add some large one in the next release, but currently wanted to get this bugfix release out asap 😓

2020-10-18 10:07 UTC, apeltzer commented on docs/usage.md
> -## Main Pipeline Arguments
Yes

2020-10-18 10:10 UTC, apeltzer commented on conf/base.config
> +      time = { check_max( 160.h * task.attempt, 'time' ) }
Can I mix labels with `withName`? Sometimes I need to only add a container for that particular process, could keep the label then to `large` as I'm already using this ... 🤔

2020-10-19 09:51 UTC, jfy133 commented on conf/base.config
> +      time = { check_max( 160.h * task.attempt, 'time' ) }
We do it in nf-core/eager and it seems to work well!

2020-11-04 17:54 UTC, apeltzer commented on main.nf
>    file("${sample_id}_assembly_QC/report.tsv") into quast_logs_ch
```suggestion
  file("${sample_id}_assembly_QC/${sample_id}_report.tsv") into quast_logs_ch
```

2020-11-05 08:23 UTC, apeltzer commented on main.nf
>    """
```suggestion
  mv ${sample_id}_assembly_QC/report.tsv ${sample_id}_assembly_QC/${sample_id}_report.tsv
  """
```

2020-11-05 08:37 UTC, jfy133 commented on assets/nf-core-bacass_logo.png
> +</body></html>
You need to check this, I know @skrakau and @MaxUlysse (I think) reported this for hteir pipelines too...

2020-11-05 08:40 UTC, jfy133 requested changes

2020-11-05 08:40 UTC, jfy133 commented on nextflow.config
> +  multiqc_config = false
Is this correct? Do you not have a custom one?

2020-11-05 09:17 UTC, ggabernet approved these changes
Looks good to me!

2020-11-05 09:22 UTC, MaxUlysse commented on assets/nf-core-bacass_logo.png
> +</body></html>
yes, I think we need to be careful with the auto-generated pngs

2020-11-05 10:06 UTC, apeltzer commented
Adressed your points @MaxUlysse / @jfy133

2020-11-05 10:06 UTC, jfy133 approved these changes

2020-11-05 10:20 UTC, apeltzer commented on CHANGELOG.md
> +## v1.1.1 nf-core/bacass: "Green Aluminium Shark" 2020/10/28
```suggestion
## v1.1.1 nf-core/bacass: "Green Aluminium Shark" 2020/11/05
```

2020-11-05 10:58 UTC, merged